# Generated by Django 2.2.7 on 2020-06-20 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='판매일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.Product')),
            ],
        ),
    ]
