# Generated by Django 2.2.7 on 2020-06-21 05:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_orderlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 5, 52, 54, 49916, tzinfo=utc), verbose_name='판매일'),
        ),
    ]
